eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/
server:
  port: 10001
spring:
  application:
    name: provider
  cloud:
      gateway:
        discovery:
          locator:
            enabled: true
            lowerCaseServiceId: true
       # uri: http://${config.server.ip}:${config.server.port}
       # name: cloudservice
       # profile: ${app.profile:test}
 # datasource:
 #   url: jdbc:mysql://47.95.202.91/myday?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
 #   username: test
  #  password: 123456
  #  driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: com.zhangq.mayday.model.domain
  mapperLocations: classpath:mapper/*/*.xml

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.95.202.91/myday?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
  username: TEST
  password: 123456

